version: "3.2"
services:
  database:
    container_name: user-database
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/user/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/user/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/user/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3320:3306"
    networks:
      - user_env
  application:
    container_name: user-application
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-database:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8020:8080"
    depends_on:
      - database
    networks:
      - user_env
networks:
  user_env:
    driver: bridge
