spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://127.0.0.1:3320/userdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
#    open-in-view: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  iss: von.com
  exp: 24*60*60*1000 #밀리초(하루)
  secret: vonwefwegerglijaldskfqhewlkghlkqjglkjlkdjfalkjaslkejglkjralkgjlerakjglkqjerlkgmqwrgkearhgkjhrakjghkjerahgkjerag